# Generated by Django 4.1.7 on 2023-03-29 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='TITLE', max_length=110, validators=[django.core.validators.MinLengthValidator(1)])),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('description', models.CharField(default='', max_length=110, validators=[django.core.validators.MinLengthValidator(1)])),
                ('topic', models.CharField(choices=[('T', 'Путешествия'), ('H', 'Здоровье'), ('S', 'Учеба'), ('E', 'События')], default='E', max_length=1)),
                ('content', models.CharField(default='', max_length=1000000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('picture', models.FileField(upload_to='users_pics_folder')),
            ],
        ),
    ]
