# Generated by Django 4.1.7 on 2023-03-29 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=110, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
